version: '3.9'
services:
  backend:
    image: example-backend
    ports:
      - '${BACKEND_PORT}:5000'
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      JWT_KEY: ${JWT_KEY}

  frontend:
    image: example-frontend
    ports:
      - '${FRONTEND_PORT}:80'
    restart: always
    environment:
      VITE_API_URL: backend:5000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
